import type { Metadata } from "next";
import "./globals.css";
import Fonts from "./components/Fonts";
import ClientBody from "./components/ClientBody";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ClientBody>
          <Fonts />
          {children}
        </ClientBody>
      </body>
    </html>
  );
}
